
<?php use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\URL;
Layout::includeLayout('header') ?>

<link rel="stylesheet" href="<?= Asset::css('/register_login.css')?>" media="screen" >

<?php
include("config.php");
session_start();

if($_SERVER["REQUEST_METHOD"] == "POST") {
    // username and password sent from form

    $myusername = mysqli_real_escape_string($db,$_POST['username']);
    $mypassword = mysqli_real_escape_string($db,$_POST['password']);

    $sql = "SELECT id FROM admin WHERE username = '$myusername' and passcode = '$mypassword'";
    $result = mysqli_query($db,$sql);
    $row = mysqli_fetch_array($result,MYSQLI_ASSOC);
    $active = $row['active'];

    $count = mysqli_num_rows($result);

    // If result matched $myusername and $mypassword, table row must be 1 row

    if($count == 1) {
        session_register("myusername");
        $_SESSION['login_user'] = $myusername;

        header("location: welcome.php");
    }else {
        $error = "Your Login Name or Password is invalid";
    }
}
?>

<div class="container">

    <div class="row">

        <!--TITULO DA PAGINA  -->
        <header class="page-header">
            <h1 class="page-title">Iniciar Sessão </h1>
        </header>

        <!--Formulario inicio sessao  -->

        <form class="iniciosessao-formulario" action="<?= Url::toRoute('login/start')?>" method="post">

            <label>Nome de utilizador </label>    <br>
            <input type='text' class="formulario-campo" name='username' title="Inserir um nome de utilizador"  placeholder="Nome utilizador" required/> <br>
            <label>Palavra-passe </label>    <br>
            <input type='password' class="formulario-campo" name='password' title="Inserir uma palavra passe"  placeholder="Password" required/>
            <br>
            <!--botao inicio sessao  -->
            <input type="button" class="btn-registo" value="Entrar"/><br>
            <br><br>
        </form>





    </div>
</div>