<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;

Layout::includeLayout('header');

?>

<!-- container -->
<div class="container">



            <h1>Voos</h1>
            <hr>
            <br>

            <img class="img-responsive" src="<?=Asset::image('ceuaviao.png') ?>">

            <h2></h2>
            <div class="tabelaPlace">
            <table class="table table-hover">
                <thead>
                <tr>
                    <th scope="col">Descrição</th>
                    <th scope="col">Capcidade</th>
                    <th scope="col">Vagas</th>
                    <th scope="col">Aeroporto</th>
                </tr>
                </tread>
            </table>
</div>
<?php
/* estabelece a ligação à base de dados */
$ligacao = new mysqli("localhost", "root", "", "ftaprojetopws");

/* verifica se ocorreu algum erro na ligação */
if ($ligacao->connect_errno) {
    echo "Falha na ligação: " . $ligacao->connect_error; 
    exit();
}

/* definir o charset utilizado na ligação */
$ligacao->set_charset("utf8");
    
/* texto sql da consulta*/
$consulta = 'SELECT * FROM hangargarage';

/* executar a consulta e testar se ocorreu erro */
if (!$resultado = $ligacao->query($consulta)) {
    echo ' Falha na consulta: '. $ligacao->error;
    $ligacao->close();  /* fechar a ligação */
}
else{
    /* percorrer os registos (linhas) da tabela e mostrar na página */
    while ($row = $resultado->fetch_assoc()){   
        echo "id: " . $row['id'] . ", Descrição: " . $row['description'] . ", Capacidade: " . $row['capacity'] .", Vagas: " . $row['places'] . ", Aeroporto: " . $row['airport'] ."<br>";
    }

$resultado->free();      /* libertar o resultado */
$ligacao->close();       /* fechar a ligação */
}
?>
