<?php use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Asset;


Layout::includeLayout('header') ?>


<link rel="stylesheet" href="<?= Asset::css('/register_login.css')?>" media="screen" >


    <div class="container">

    <div class="row">

    <!--TITULO DA PAGINA  -->
        <header class="page-header">
            <h1 class="page-title">Introduzir Voo </h1>
        </header>

        <!--Formulario para introduzir os voos  -->
        <form class="registo-formulario" action="<?= Url::toRoute('flights/store')?>" method="post">

            <label> Insira o número do voo </label>  <br>
            <input type='text' class="formulario-campo" name='numberflight' title="Inserir o número do voo" maxlength="100" placeholder="Número de voo" required/> <br>

            <label> Insira o preço do voo </label>  <br>
            <input type='text' class="formulario-campo" name='price' title="Inserir o preço do voo" maxlength="100" placeholder="Preço do voo" required/> <br>

            <label> Insira a origem do voo</label>  <br>
            <input type='text' class="formulario-campo" name='origin' title="Inserir a origem do voo" maxlength="100" placeholder="Origem do voo" required/> <br>

            <label >Insira o destino do voo </label>  <br>
            <input type='text' class="formulario-campo" name='destiny' title="Inserir o destino do voo"  placeholder="Destino do voo" required/> <br>

            <label> Insira a data de partida</label>  <br>
            <input type='date' class="formulario-campo" name='date' title="Inserir a data de partida"  placeholder="Data de partida" required/> <br>

            <label> Insira a hora de partida</label>  <br>
            <input type='time' class="formulario-campo" name='departuretime' title="Inserir a hora de partida"  placeholder="Hora de partida" required/> <br>

            <label> Insira a hora de chegada</label>  <br>
            <input type='time' class="formulario-campo" name='arrivaltime' title="Inserir a hora de chegada"  placeholder="Hora de chegada" required/> <br>

            <label>Insira o avião (referência) </label>    <br>
            <input type='text' class="formulario-campo" name='airplane' title="Inserir a referência do avião"  placeholder="Referência do avião" required/> <br>

            <label>Insira o aeroporto de origem</label>    <br>
            <input type='text' class="formulario-campo" name='originairport' title="Inserir o aeroporto de origem"  placeholder="Aeroporto de origem" required/> <br>

            <label>Insira o aeroporto de destino </label>    <br>
            <input type=text class="formulario-campo" name='destinyairport' title="Inserir o aeroporto de destino"  placeholder="Aeroporto de destino" required/> <br>

            <!--botao para registar o voo -->
            <input type="submit" class="btn-registo" value="Introduzir Voo"/><br>
            <br><br>
        </form>



    </div>
    </div>




