<?php use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Asset;


Layout::includeLayout('header') ?>


<link rel="stylesheet" href="<?= Asset::css('/register_login.css')?>" media="screen" >


    <div class="container">

    <div class="row">

    <!--TITULO DA PAGINA  -->
        <header class="page-header">
            <h1 class="page-title">Introduzir Voo </h1>
        </header>




    </div>
    </div>




