<?php use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Post;



Layout::includeLayout('header')?>


<link rel="stylesheet" href="<?= Asset::css('/register_login.css')?>" media="screen" >


<div class="container">

    <div class="row">

    <!--TITULO DA PAGINA  -->
        <header class="page-header">
            <h1 class="page-title">Administrador  </h1>
        </header>


        <br>
        <!--botao para ir para pagina iniciar sessao  -->
        <a class="btn-iniciosessao"  href="<?= Url::toRoute('home/login')?>">Iniciar Sessão</a>

        <a class="btn-iniciosessao"  href="<?= Url::toRoute('administrator/airports')?>">Introduzir Aeroporto</a>
        <br><br>


    </div>



</div>


